### ISSUE TITLE
Evaluation arguments with reference classes

### ISSUE THREAD

**Issue by christophergandrud** [tidyverse/rlang#226]
We've identified an issue with the dev build (0.1.1.9000) of rlang for evaluation of arguments with reference classes. For example:

```r
devtools::install_github("tidyverse/rlang")
library(rlang)
library(Zelig)

zelig(mpg ~ hp, data = mtcars, model = "ls")

## Error in mpg ~ hp : unused arguments (formula = mpg, data = hp)
```

A git bisect (https://github.com/izahn/rlang/commit/529727a355f8688a6a18b15a833071e78e0f2621) suggests that the issue appeared with the introduction of `base_tilde_eval`.

More details are at: https://github.com/IQSS/Zelig/issues/292#issuecomment-319497471

**Comment by lionel-** [comment]
That's because our `~` definition takes two named arguments from that commit on, instead of `...`. You are probably doing something like this in your package:

```r
args <- list(formula = mpg, data = hp)
do.call("~", args)
```

You could work around this by unnaming the arguments.

I think I know how to fix this on the rlang side, though the `do.call()` with named arguments only works with base formulas because of an implementation detail of the tilde operator, not because it's an intended feature.

**Comment by christophergandrud** [comment]
Thanks @lionel- for your quick reply!

Removing the named arguments does prevent this error. However, it create a lot of other problems with the function later on as it does things like check `if (missing(ARG))` which requires named arguments.

It would be amazing if the solution was on the rlang side to enable the use of named arguments in the usual R fashion. Is there any way I can help move this along?

**Comment by lionel-** [comment]
I wouldn't say that calling the `~` operator with named arguments is the usual R fashion ;)

**Comment by christophergandrud** [comment]
That change seems to work well. Thanks!
