### ISSUE TITLE
Export .env?

### ISSUE THREAD

**Issue by gergness** [tidyverse/rlang#269]
Is it possible to export `.env` along with `.data` so I can use it in a package without R command check warnings?

**Comment by lionel-** [comment]
We're still not sure about the place of `.env` in the tidy eval framework. It will always remain available, but it seems better to use `!!` to evaluate stuff from the environment. The only time you should use `.env` is when you want to retrieve a variable from the environment *and* you want it to happen at evaluation time rather than quoting time (i.e. you need more laziness).

Note that you can use `utils::globalVariables()` to declare `.env` to R CMD check.

**Comment by gergness** [comment]
Thanks, makes sense. I liked the symmetry of converting something like:
```
y <- 1:3
df <- data.frame(x = 1:5)
dplyr::filter(df, x %in% y)
```
to
```
dplyr::filter(df, .data$x %in% .env$y)
```
But using `!!` works too. (Coming at it from this perspective, I forgot about it)
