### ISSUE TITLE
Using as_data_mask reduces overhead by surprising amount

### ISSUE THREAD

**Issue by hadley** [tidyverse/rlang#372]
``` r
library(rlang)

n <- 1000
q1 <- quo(runif(n))
d_mtcars <- as_data_mask(mtcars)

tibble::as_tibble(summary(microbenchmark::microbenchmark(
  eval_tidy(q1, mtcars),
  as_data_mask(mtcars), 
  eval_tidy(q1, d_mtcars)
)))
#> # A tibble: 3 x 9
#>   expr                      min    lq  mean median    uq   max neval cld  
#>   <fct>                   <dbl> <dbl> <dbl>  <dbl> <dbl> <dbl> <dbl> <chr>
#> 1 eval_tidy(q1, mtcars)   56.5  65.6  68.4   67.8  69.4  165     100 "  c"
#> 2 as_data_mask(mtcars)     3.75  4.45  5.70   5.62  6.02  19.2   100 "a  "
#> 3 eval_tidy(q1, d_mtcars) 29.8  35.8  37.6   37.4  38.6  101     100 " b "
```

Why does `eval_tidy(q1, mtcars)` take 68µs, when `as_data_mask(mtcars)` + `eval_tidy(q1, d_mtcars)` takes 42µs?

**Comment by lionel-** [comment]
This is because you created a data mask but didn't run `data_mask_clean()` on it. I do wonder what's the right default here. Cleaning it is necessary in dplyr to avoid dangling pointers for the active bindings but maybe that's not the preferred default. Should formulas and functions created in the data mask have access to the data after evaluation is done?

Note that cleaning the data mask involves calling into the R function `base::remove()` as there is no C API for it, which might explain the unexpected overhead.

**Comment by lionel-** [comment]
> Note that cleaning the data mask involves calling into the R function base::remove() as there is no C API for it, which might explain the unexpected overhead.

Oh we could just rechain the mask to the lexical environment and let the GC collect the now dangling environments.

**Comment by krlmlr** [comment]
I need to review data masks before giving an informed answer.

**Comment by hadley** [comment]
At a minimum, the documentation needs to describe what `data_mask_clean()` does

**Comment by hadley** [comment]
I don't know what cleaning the data mask does, so I can't say for sure whether this should be the default, or something that you should have to do explicitly. For most purposes, the overhead isn't going to be too awful, especially since if you're calling it a tight loop, you'll want to create the data mask manually anyway.

**Comment by lionel-** [comment]
We also have to think about data mask leaking (e.g. through closures/formulas) within nested quosures. Currently the data mask is recycled and rechained to lexical contexts, and when evaluation is done the mask is chained to the environment supplied to `eval_tidy()` as `env`.

It looks like we should create new masks for each nested quosures so leaked environments inherit from the quosure environment rather than eval_tidy's `env` argument.

**Comment by krlmlr** [comment]
Do data masks replace the functionality from *bindr* and *bindrcpp*, at least for *dplyr*?

https://github.com/krlmlr/bindrcpp/issues/2 feels relevant.

I still think we can make objectables fast, with a small change to R-core. (One reason for their relatively weak performance is a string comparison (24 bytes) on every operation, I feel this can be replaced by a pointer comparison.) Who from R-core could help make this happen?

**Comment by lionel-** [comment]
> Do data masks replace the functionality from bindr and bindrcpp, at least for dplyr?

bindr and bindrcpp create a data mask manually (previously called an overscope) and clean those with `rlang::data_mask_clean()`.

I still wonder whether the data should be left in there by default though (ideally)...?

In any case I think stranding the mask environments should be enough to avoid problems as users would have to go out of their way to leak the intermediate environments of the data mask (those that contain the active bindings in dplyr).


> Who from R-core could help make this happen?

Maybe Duncan since he implemented object tables?
